baseURL = "https://nowead.github.io/"
languageCode = "ko-kr"
title = "Nowead's Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  # PaperMod í•„ìˆ˜ ì„¤ì •ë“¤
  [params.homeInfoParams]
    Title = "ì•ˆë…•í•˜ì„¸ìš” ğŸ‘‹"
    Content = "ê°œë°œ ë¸”ë¡œê·¸ì— ì˜¤ì‹  ê²ƒì„ í™˜ì˜í•©ë‹ˆë‹¤."

  # ì†Œì…œ ë§í¬
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/nowead"